image:
  repository: $CI_REGISTRY_IMAGE/hasura
  tag: master

fullnameOverride: hasura

deployment:
  livenessProbe:
    path: /healthz
    initialDelaySeconds: 30
    periodSeconds: 20
  readinessProbe:
    path: /healthz
    initialDelaySeconds: 30
    periodSeconds: 20

  resources:
    requests:
      cpu: 5m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1024Mi

  envFrom:
    - configMapRef:
        name: hasura-env
    - secretRef:
        name: hasura-env

ingress:
  enabled: false
