name: "Create database"
description: "Create database and user using random secure"
inputs:
  kubeconfig:
    description: "The Kubernetes authentication configuration"
  rancherId:
    description: "The Rancher project ID, usually secrets.RANCHER_PROJECT_ID"
  socialgouvBaseDomain:
    description: "The base domain name, usually secrets.SOCIALGOUV_BASE_DOMAIN"
  environment:
    description: "The deployment environment (dev | preprod | prod)"
  adminPgSecret:
    description: "PG Secret admin secretRefName"
  pgUserAddHostSuffix:
    description: "Add user suffix `@hostname`, muste be true for Azure, false for Scaleway, if not provided it autodetect azure using PGHOST"
  jobNamespace:
    description: "Namespace for job to mount secrets, in future, this will be ${project}-ci, for now it's ${project}-${branch-slug}"

runs:
  using: "composite"
  steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get project and namespace names
      shell: bash
      run: |
        if test -f ".github/dev.env"; then
          cat ".github/dev.env" >> $GITHUB_ENV
        fi

        PROJECT_NAME=${GITHUB_REPOSITORY##*/}
        BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
        BRANCH_SLUG=$(npx @socialgouv/env-slug ${BRANCH_NAME})
        NAMESPACE=${PROJECT_NAME}-${BRANCH_SLUG}
        JOB_NAMESPACE=${PROJECT_NAME}-ci
        if [ "$SOCIALGOUV_PRODUCTION" ]; then
          DB_SECRET_NAME=pg-user
        elif [ "$SOCIALGOUV_PREPRODUCTION" ]; then
          DB_SECRET_NAME=pg-user-preprod
        else
          DB_SECRET_NAME="pg-user-${BRANCH_SLUG}"
        fi

        echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        echo "BRANCH_SLUG=$BRANCH_SLUG" >> $GITHUB_ENV
        echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV
        echo "JOB_NAMESPACE=$JOB_NAMESPACE" >> $GITHUB_ENV
        echo "DB_SECRET_NAME=$DB_SECRET_NAME" >> $GITHUB_ENV

    - name: Create kubernetes config
      shell: bash
      run: |
        mkdir -p ~/.kube
        touch ~/.kube/config
        echo ${{ inputs.kubeconfig }} | base64 -d > ~/.kube/config

    - uses: c-hive/gha-yarn-cache@v2

    - name: Install global JS dependencies
      shell: bash
      run: yarn global add ts-node typescript

    - name: Install action JS dependencies
      shell: bash
      run: yarn --prefer-offline --cwd ${{ github.action_path }} install

    - name: Generate k8s job's manifests
      shell: bash
      run: |
        cd ${{ github.action_path }}

        yarn run -s values > values.json

        cat templates/namespace.gtpl | npx gomplate -d values.json > namespace.yml
        cat templates/job.create-db.gtpl | npx gomplate -d values.json > job.create-db.yml

        # if [ -n "$(kubectl -n $NAMESPACE get secret $DB_SECRET_NAME 2>/dev/null)" ]; then
        #   echo "secret named '$DB_SECRET_NAME' already exists in namespace '$NAMESPACE'"
        # else
        #   scripts/create-secret
        # fi

        # scripts/copy-secret

        # kubectl delete --namespace=$JOB_NAMESPACE job/create-db-user || true
        # kubectl apply --namespace=$JOB_NAMESPACE -f create-db.yml

        # scripts/wait-job job/create-db-user

      env:
        PG_USER_ADD_HOST_SUFFIX: ${{ inputs.pgUserAddHostSuffix || env.PG_USER_ADD_HOST_SUFFIX || '' }}
        JOB_IMAGE: ghcr.io/socialgouv/docker/azure-db
        JOB_IMAGE_TAG: 6.68.0
        ENVIRONMENT: ${{ inputs.environment }}
        SOCIALGOUV_CONFIG_PATH: /tmp/autodevops/config.json
        RANCHER_PROJECT_ID: ${{ inputs.rancherId || env.RANCHER_PROJECT_ID }}
        SOCIALGOUV_BASE_DOMAIN: ${{ inputs.socialgouvBaseDomain || env.SOCIALGOUV_BASE_DOMAIN }}
