app:
  enabled: true
  imagePackage: app
  probesPath: /healthz
  certSecretName: app-crt
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap

hasura:
  enabled: true
  # waitForPostgres: true
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: hasura-sealed-secret
    - configMapRef:
        name: hasura-configmap

pgweb:
  enabled: true
  certSecretName: pgweb-crt
