# See https://github.com/SocialGouv/helm-charts/tree/master/charts/app

image:
  repository: $CI_REGISTRY_IMAGE
  tag: master

fullnameOverride: app

deployment:

  livenessProbe:
    initialDelaySeconds: 30

  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 64Mi

  env:
    - name: FRONTEND_PORT
      value: "${FRONTEND_PORT}"
    - name: NODE_ENV
      value: production

ingress:
  enabled: true
