version: "3.6"
services:
  postgres:
    image: postgres:10
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  graphql-engine:
    build: hasura
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    env_file:
      - .env.development
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log

  app:
    build: .
    depends_on:
      - "graphql-engine"
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    environment:
      GRAPHQL_ENDPOINT: http://graphql-engine:8080/v1/graphql

volumes:
  db_data:
