hasura:
  needs: [build-hasura,db]

pgweb:
  needs: [db]

jobs-dev:
  runs:
    db:
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/create-db@master
      with:
        pgAdminSecretRefName: pg-scaleway

jobs-deactivate:
  enabled: false
  runs:
    drop-db:
      # use: SocialGouv/kontinuous/plugins/fabrique/jobs/deactivate@master
      use: SocialGouv/kontinuous/plugins/fabrique/jobs/drop-db@master
      with:
        pgAdminSecretRefName: pg-scaleway
