kind: ConfigMap
apiVersion: v1
metadata:
  name: app-configmap
data:
  NODE_ENV: "production"
  GRAPHQL_ENDPOINT: "http://hasura/v1/graphql"
  ACCOUNT_MAIL_SENDER: "contact@fabrique.social.gouv.fr"
  FRONTEND_PORT: "3030"
  PRODUCTION: "false"
  NEXT_PUBLIC_MATOMO_URL: https://matomo.fabrique.social.gouv.fr
  NEXT_PUBLIC_MATOMO_SITE_ID: "15"
  SENTRY_DSN: https://24f5b07f17a544b1b76ac0766ee68020@sentry.fabrique.social.gouv.fr/27
