components:
  app: true
  hasura: true
  pgweb: true
  jobs: true

app:
  imagePackage: app
  probesPath: /healthz
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap

hasura:
  needs: [create-db]
  # waitForPostgres: true
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: hasura-sealed-secret
    - configMapRef:
        name: hasura-configmap

pgweb:
  needs: [create-db]

jobs:
  repositoryUrl: https://github.com/SocialGouv/sample-next-app.git
  runs:
    - name: create-db
      image: socialgouv/psql
      run: /bin/create-db
