components:
  jobs: true

hasura:
  needs: [db]

pgweb:
  needs: [db]

jobs:
  repositoryUrl: https://github.com/SocialGouv/sample-next-app.git
  runs:

    # - name: db
    #   use: SocialGouv/uses/create-db@v1
    #   with:
    #     pgAdminSecretRefName: pg-scaleway

    # test include recursive action
    - name: db
      use: SocialGouv/uses/a.yaml@jobs-workflow
      with:
        pgAdminSecretRefName: pg-scaleway
