components:
  app: true
  hasura: true
  pgweb: true

app:
  envFrom:
    - secretRef:
        name: {{ .Values.global.pgSecretName }}
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap

hasura:
  envFrom:
    - secretRef:
        name: {{ .Values.global.pgSecretName }}
    - secretRef:
        name: hasura-sealed-secret
    - configMapRef:
        name: hasura-configmap
