root: true
overrides:
  - files: "*.js"
    extends:
      - "@socialgouv/eslint-config-recommended"
  - files: "*.ts"
    extends:
      - "@socialgouv/eslint-config-typescript"
    rules:
      "@typescript-eslint/no-use-before-define": off
      import/no-unresolved:
        - error
        - ignore:
            - "^@socialgouv/kosko-charts/"
