#!/bin/bash

if [[ -z "${SENTRY_TOKEN}" ]]; then
  echo "Expect SENTRY_TOKEN to be defined";
  exit 1;
fi

echo -n "${SENTRY_TOKEN}" \
  | parallel --pipe --tee -v {} ::: \
    "sealed_as app-env ${0}"
