#!/bin/bash

if [[ -z "${SMTP_EMAIL_USER}" ]]; then
  echo "Expect SMTP_EMAIL_USER to be defined";
  exit 1;
fi

echo -n "${SMTP_EMAIL_USER}" \
  | parallel --pipe --tee -v {} ::: \
    "sealed_as app-env ${0}"
