#!/bin/bash

if [[ -z "${SMTP_EMAIL_PASSWORD}" ]]; then
  echo "Expect SMTP_EMAIL_PASSWORD to be defined";
  exit 1;
fi

echo -n "${SMTP_EMAIL_PASSWORD}" \
  | parallel --pipe --tee -v {} ::: \
    "sealed_as app-env ${0}"
