global:
  registry: harbor.fabrique.social.gouv.fr

app:
  # chart: fabrique.app
  needs: [build-app]
  imagePackage: app
  probesPath: /healthz
  certSecretName: app-crt
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap

hasura:
  needs: [build-hasura]
  # waitForPostgres: true
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: hasura-sealed-secret
    - configMapRef:
        name: hasura-configmap

pgweb:
  certSecretName: pgweb-crt

jobs:
  runs:

    - name: build-app
      use: SocialGouv/kube-workflow/jobs/build@feat-outputs
      with:
        registrySecretRefName: harbor
        imagePackage: app

    - name: build-hasura
      use: SocialGouv/kube-workflow/jobs/build@feat-outputs
      with:
        registrySecretRefName: harbor
        imagePackage: hasura
        context: hasura


# job-say-hello:
#   foo: barjo

# keycloak: {}
