global:
  registry: harbor.fabrique.social.gouv.fr

app:
  # chart: fabrique.app # implicit
  needs: [build-app]
  imagePackage: app
  probesPath: /healthz
  certSecretName: app-crt
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap

hasura:
  needs: [build-hasura]
  envFrom:
    - secretRef:
        name: "{{ .Values.global.pgSecretName }}"
    - secretRef:
        name: hasura-sealed-secret
    - configMapRef:
        name: hasura-configmap

pgweb:
  certSecretName: pgweb-crt

jobs:
  runs:
    build-app:
      use: build
      with:
        registrySecretRefName: harbor
        imagePackage: app

    build-hasura:
      use: build
      with:
        registrySecretRefName: harbor
        imagePackage: hasura
        context: hasura


secrets: {}

# keycloak: {}
