---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: hasura-secrets
  creationTimestamp:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
spec:
  template:
    metadata:
      name: hasura-secrets
      creationTimestamp:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
    type: Opaque
  encryptedData:
    HASURA_GRAPHQL_ADMIN_SECRET: AgBCS0EWQIVo8s8o55WH2UxaX+qkT6ipRrurqDWQI3ZVXFwQhorcQylYRIBzaJO6egHQ/I3o5repI/OG3BSOWM0Nb5dIYYFQaah5z1utUHCVda2vPZfLvCGt2eJzoMNNgGLwaTc9Pu7dDi/aqsrZpbMw7gNxd8Cgc9GD3HVxBat4uiOnaQkrYys4moSSq30E9MHzKf0qaUbzKX/j5p4oXMfnlTOZFdHKZcTpq2GpE7dZcrtLmTxXSX15+EbCU3nUVuWoFmyFVGPuClPWH9ya6cQhpV3TsCTyjQ3Ib5PkKFdItAst/HoHPxoMfF+lN2R9U/3aem2pwpjSwdU6HjCqkvNPYidwdkhLD6mB1QGO/PW0wd9T+EWdYBamirBh/5C614bij81gshmCUV5BLUvrLylCxkeSnIDtDjkS4BX5Qj6cBmAkXKA2zn9GdOnNXgU3IGtPTLfMh0BDevmya5aWYBhelEouwNachg5X08odMSjA/FlczK8/wlYvP6LR8qZfoRFMYbbLZHMlNJljMfNezszYGprUBtG0EWhZMoTz9iQYUuk6kQEgA+2DyDzx51YRFgctaa2yfK0Sh7j9M4jAwR6l12a42/1vDCXdyPLMwuzcAaVWgKwuJ9S3QUn1n4hr9itKD1/dpnY7q+UsGGuyxKAwZx0nqPlZxcp4CNzk+cWLJl2B3wOOhqZaKMKjZdsuQqjnzUclJ1mO1gGKxnD7ZS3/RqD9H7DmahK6SmGWg490Q6ibWor3dcZcgHbO6A==
    HASURA_GRAPHQL_JWT_SECRET: AgAnThMc6uuayn1BR4rLy65IoFDsv8pzBpphbYxf36e4OJooSi9s2upWe8g3HpVfdb5SthH77uw+64Ks+Tvku1gHrUOOXh89F+RS1mLwBfNhe4Nlf55AosasYsUOjE5mWOd0Czdp723ujL9T1SoZNyGeGyG2ZPxR+clgBJIgX5fRMvfi76SSq5trUasItHflHp+io2leMD8QBB0jukLf8vmHHCZ36S1hwtISj7NMHtiv4bl2AQPj6KjyO2U0AB+Uf+Un21RwCRsXv4mDkKNZAGSMn67IkqLRK02TFJQRz4qn+WrX4DPkgNG+fELYHBK0CSi8orSN07Z0qY4y86IYbXRiqJDDKIXq6jNQ2V3Ffox8uNNPk8BJ4lrxz4Bn9r9/rTWRLS70Uzv+OXViJ2xcb4HxBZFSKucOVK4Gx8kFf5xoKd6LV6g6kbjtYQUR4FGQihvZYsDrr5qGv1rxHO7EkY4o9Hre2iHVQJ08imfDoXscfzeJC9lxo/e5M7LusDtIkzwkMkmsv8WXMlGjfg4JoYiQzVA8oMsmeWQLHNdJUdSkZF8tFc3skvgYEeMuDi89KRiuCOwnShrVLzPzYbWO+7dwnyay5NVvtvNE9kXYn5U4EwGExeLGWoRRrDCOUM9sgwAJF7AcDcQUQ+MWupWacW7YE+VjBMuDmJR+1Gx9qDXGUspG1DkDfKqLCxT1L2RoMlbIfubACEYYbZ5IiooqjwbHCMUzbr4aRNSM2C3KqN8wSlB18xVfrgVpWYqZFtXWjJAgvLbn5Pi6ryaBPy/adnlBpGf1S2EakV9uR6gdpsKR1yTmzNT7MCIiInzvq/KijQCiJwAyqIkpU+tQv+HInHxWZQ==
