hasura:
  needs: [db]

pgweb:
  needs: [db]

jobs:
  enabled: true
  runs:
    - name: db
      use: SocialGouv/kube-workflow/jobs/create-db@master
      with:
        pgAdminSecretRefName: pg-scaleway
