#!/usr/bin/env bash

if [ "$SOCIALGOUV_PRODUCTION" ]; then
  DB_SECRET_NAME=pg-user
elif [ "$SOCIALGOUV_PREPRODUCTION" ]; then
  DB_SECRET_NAME=pg-user-preprod
else
  DB_SECRET_NAME="pg-user-${BRANCH_SLUG}"
fi
kubectl get secret $DB_SECRET_NAME --namespace=$NAMESPACE -o yaml \
  | sed 's/namespace: .*//' \
  | kubectl -n $JOB_NAMESPACE apply -f -
