name: test harbor

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - v*
      
      
jobs:
  register:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: harbor.fabrique.social.gouv.fr
          username: "robot$sample-next-app+github"
          password: ${{ secrets.HARBOR_PASSWORD }}
