name: "NodeSecure Continuous Integration"
on: [push]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: NodeSecure/ci-action@v1.0
        with:
            strategy: npm
            vulnerabilities: medium
            warnings: off
            reporters: console
