name: Preproduction

on:
  push:
    branches:
      - master
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: preproduction

jobs:

  build-app:
    name: Build & Register App
    runs-on: ubuntu-latest
    steps:
      - name: Application
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          imagePackage: app
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: preprod

  build-hasura:
    runs-on: ubuntu-latest
    name: Build & Register Hasura
    steps:
      - name: Hasura
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          dockercontext: ./hasura
          dockerfile: ./hasura/Dockerfile
          token: ${{ secrets.GITHUB_TOKEN }}
          imagePackage: hasura
          environment: preprod

  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [build-app,build-hasura]
    environment:
      name: preproduction
      url: https://sample-next-app-preprod.dev.fabrique.social.gouv.fr
    steps:

      - name: Use autodevops deployment
        uses: SocialGouv/kube-workflow@master
        with:
          environment: "preprod"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
