name: Production

on:
  push:
    tags:
      - v*

concurrency:
  group: preproduction
  cancel-in-progress: true

jobs:
  ##############################################################################
  ## BUILD AND REGISTER DOCKER IMAGE
  ##############################################################################
  register:
    name: Build & Register docker images
    runs-on: ubuntu-latest
    steps:
      - name: Get project name
        run: |
          echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Application
        uses: SocialGouv/actions/harbor-build-register@master
        with:
          imageName: ${{ env.project }}/app
          harborUsername: ${{ secrets.HARBOR_USERNAME }}
          harborPassword: ${{ secrets.HARBOR_PASSWORD }}
          
      - name: Hasura
        uses: SocialGouv/actions/harbor-build-register@master
        with:
          imageName: ${{ env.project }}/hasura
          dockercontext: ./hasura
          dockerfile: ./hasura/Dockerfile
          harborUsername: ${{ secrets.HARBOR_USERNAME }}
          harborPassword: ${{ secrets.HARBOR_PASSWORD }}

  ##############################################################################
  ## GENERATE PREPRODUCTION MANIFESTS
  ##############################################################################
  manifests:
    name: Preproduction manifests
    runs-on: ubuntu-latest
    steps:
      - name: Use k8s manifests generation
        uses: SocialGouv/actions/k8s-manifests@v1
        with:
          environment: "preprod"
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvbaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
          
  ##############################################################################
  ## DEPLOY PREPRODUCTION APPLICATION
  ##############################################################################
  deploy-preprod:
    name: Deploy preproduction
    runs-on: ubuntu-latest
    needs: [register, manifests]
    environment:
      name: preproduction
      url: https://sample-next-app-preprod.dev.fabrique.social.gouv.fr
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-deploy@v1
        with:
          environment: "preprod"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          
  ##############################################################################
  ## DEPLOY PRODUCTION APPLICATION
  ##############################################################################
  deploy-prod:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: [deploy-preprod]
    environment:
      name: production
      url: https://sample-next-app.fabrique.social.gouv.fr
    steps:
      - name: Use k8s manifests generation
        uses: SocialGouv/actions/k8s-manifests@v1
        with:
          environment: "prod"
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-deploy@v1
        with:
          environment: "prod"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
