name: Production

on:
  push:
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:

  register:
    name: Build & Register docker images
    runs-on: ubuntu-latest
    steps:
      - name: Application
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: sample-next-app/app

      - name: Hasura
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          dockercontext: ./hasura
          dockerfile: ./hasura/Dockerfile
          token: ${{ secrets.GITHUB_TOKEN }}
          imageName: sample-next-app/hasura

  deploy-prod:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: [register]
    environment:
      name: production
      url: https://sample-next-app.fabrique.social.gouv.fr
    steps:
      - name: Use autodevops deployment
        uses: SocialGouv/actions/autodevops-helm-deploy@v1
        with:
          environment: "prod"
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
          socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
